ALTER TABLE projects
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE clients
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE creators
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE graphics
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE contacts
  MODIFY COLUMN id VARCHAR(36) NOT NULL;

ALTER TABLE posts
  MODIFY COLUMN id VARCHAR(36) NOT NULL;
